# Generated by Django 5.1 on 2024-10-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.BigIntegerField(verbose_name='admin id')),
                ('link', models.TextField(verbose_name='link')),
                ('bot_token', models.TextField()),
                ('group1', models.BigIntegerField(verbose_name='1 gruppa')),
                ('group2', models.BigIntegerField(verbose_name='2 gruppa')),
                ('group3', models.BigIntegerField(verbose_name='3 gruppa')),
                ('price', models.IntegerField(verbose_name='kurs narxi')),
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Adminlar',
            },
        ),
    ]
