# Generated by Django 5.1 on 2024-10-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name': 'Admin', 'verbose_name_plural': 'Admin'},
        ),
        migrations.AlterField(
            model_name='admin',
            name='link',
            field=models.CharField(max_length=150, verbose_name='link'),
        ),
    ]
