# Generated by Django 5.1 on 2024-10-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_admin_bot_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='bot_token',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='bot token'),
        ),
    ]
