# Generated by Django 5.1 on 2024-10-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_admin_bot_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images', verbose_name='qr code')),
                ('number', models.DecimalField(decimal_places=0, max_digits=16, verbose_name='karta raqami')),
                ('username', models.CharField(max_length=150, verbose_name='ism-familiya')),
            ],
            options={
                'verbose_name': 'Karta',
                'verbose_name_plural': 'Kartalar',
            },
        ),
    ]
