# Generated by Django 5.1 on 2024-10-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oylik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200, verbose_name='foydalanuvchi')),
                ('user_id', models.BigIntegerField(verbose_name='telegram id')),
                ('gruppa', models.IntegerField(verbose_name='gruppa')),
                ('status', models.BooleanField(verbose_name='status')),
                ('narx', models.IntegerField(verbose_name='narx')),
                ('date', models.IntegerField(verbose_name='sana')),
                ('info', models.BooleanField(verbose_name='malumot')),
                ('month', models.IntegerField(verbose_name='oy')),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(verbose_name='telegram id')),
                ('username', models.CharField(max_length=100, verbose_name='username')),
                ('fullname', models.CharField(max_length=100, verbose_name='ism-familiya')),
                ('phone', models.DecimalField(decimal_places=0, max_digits=13, verbose_name='tel raqam')),
                ('start', models.DateTimeField(auto_now_add=True, verbose_name='start bot')),
                ('toifa', models.TextField(verbose_name='toifa')),
                ('birthday', models.CharField(max_length=10, verbose_name="tug'ilgan sana")),
                ('region', models.CharField(max_length=20, verbose_name='yashash hududi')),
                ('secodn_phone', models.DecimalField(decimal_places=0, max_digits=13, verbose_name="qo'shimcha tel")),
                ('age', models.IntegerField(verbose_name='yosh')),
                ('goal', models.TextField(verbose_name='maqsad')),
                ('monthly', models.CharField(max_length=20, verbose_name='oylik')),
            ],
            options={
                'verbose_name': "O'quvchi",
                'verbose_name_plural': "O'quvchilar",
            },
        ),
    ]
