# Generated by Django 5.1 on 2024-10-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_oylik_people'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'Karta', 'verbose_name_plural': 'Karta'},
        ),
        migrations.AlterModelOptions(
            name='oylik',
            options={'verbose_name': 'Oylik', 'verbose_name_plural': 'Oyliklar'},
        ),
        migrations.AlterField(
            model_name='oylik',
            name='info',
            field=models.DecimalField(decimal_places=0, max_digits=1, verbose_name='malumot'),
        ),
        migrations.AlterField(
            model_name='oylik',
            name='status',
            field=models.DecimalField(decimal_places=0, max_digits=1, verbose_name='status'),
        ),
    ]
