# Generated by Django 5.1 on 2024-10-09 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_people_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='gruppa nomi')),
                ('group_id', models.BigIntegerField(verbose_name='gruppa id')),
            ],
            options={
                'verbose_name': 'Gruppa',
                'verbose_name_plural': 'Gruppalar',
            },
        ),
        migrations.AddField(
            model_name='people',
            name='gruppa',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main.group'),
            preserve_default=False,
        ),
    ]
