# Generated by Django 4.2 on 2024-10-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_group_people_gruppa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name': 'Admin', 'verbose_name_plural': 'Adminlar'},
        ),
        migrations.RenameField(
            model_name='people',
            old_name='secodn_phone',
            new_name='second_phone',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='group1',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='group2',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='group3',
        ),
        migrations.AlterField(
            model_name='people',
            name='gruppa',
            field=models.CharField(max_length=100, verbose_name='gruppa'),
        ),
    ]
