# Generated by Django 4.2 on 2024-10-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_admin_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='second_phone',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=13, null=True, verbose_name="qo'shimcha tel"),
        ),
    ]
