# Generated by Django 4.2 on 2024-10-09 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_people_second_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Gruppa',
        ),
    ]
