# Generated by Django 5.1.2 on 2024-10-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_group_gruppa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='username'),
        ),
    ]
