# Generated by Django 5.1.2 on 2024-10-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_people_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='gruppa_id',
            field=models.BigIntegerField(default=2, verbose_name='gruppa id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='oylik',
            name='gruppa',
            field=models.BigIntegerField(verbose_name='gruppa'),
        ),
        migrations.AlterField(
            model_name='people',
            name='gruppa',
            field=models.CharField(max_length=100, verbose_name='gruppa nomi'),
        ),
    ]
