# Generated by Django 5.1.2 on 2024-10-21 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_oylik_gruppa'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='bot_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='BotButtonReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons_reply', to='main.botmessage')),
            ],
        ),
        migrations.CreateModel(
            name='BotButtonInlyne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('callback_data', models.CharField(max_length=100)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons_inlyne', to='main.botmessage')),
            ],
        ),
    ]
