# Generated by Django 5.1.2 on 2024-10-22 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_botmessage_botbuttonreply_botbuttoninlyne'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botbuttoninlyne',
            options={'verbose_name': 'Bot ichki tugma', 'verbose_name_plural': 'Bot ichki tugmalar'},
        ),
        migrations.AlterModelOptions(
            name='botbuttonreply',
            options={'verbose_name': 'Bot tugma', 'verbose_name_plural': 'Bot tugmalar'},
        ),
        migrations.AlterModelOptions(
            name='botmessage',
            options={'verbose_name': 'Bot Xabar', 'verbose_name_plural': 'Bot Xabarlar'},
        ),
        migrations.AddField(
            model_name='gruppa',
            name='price',
            field=models.IntegerField(default=2, verbose_name='kurs narxi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='botbuttoninlyne',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons_inline', to='main.botmessage'),
        ),
        migrations.AlterField(
            model_name='botmessage',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='card',
            name='photo',
            field=models.ImageField(upload_to='images/', verbose_name='qr code'),
        ),
        migrations.AlterField(
            model_name='people',
            name='phone',
            field=models.DecimalField(decimal_places=0, max_digits=13, verbose_name='telefon raqam'),
        ),
    ]
