# Generated by Django 5.1.2 on 2024-10-22 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_botbuttoninlyne_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='price',
        ),
    ]
